stages:
  - build_docs
  - build_image
  - deploy

cache: &global_cache
  key: ${CI_COMMIT_BRANCH}
  paths:
    - .cache/pip
    - .venv
  policy: pull

build_docs:
  stage: build_docs
  only:
    - tags
  tags:
    - protojour
    - shell
    - memoriam
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - poetry config virtualenvs.in-project true
    - poetry install --only docs
    - cd docs
    - poetry run make html
  artifacts:
    paths:
      - docs/_build/

build_docs_caddy_image:
  stage: build_image
  only:
    - tags
  tags:
    - protojour
    - shell
    - memoriam
  script:
    - cd docs
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build --tag $CI_REGISTRY_IMAGE/docs:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE/docs:latest .
    - docker push --all-tags $CI_REGISTRY_IMAGE/docs

trigger_infrastructure_docs:
  stage: deploy
  only:
    - tags
  variables:
    UPSTREAM_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/docs
    UPSTREAM_COMMIT_TAG: $CI_COMMIT_TAG
    UPSTREAM_PROJECT_NAME: $CI_PROJECT_NAME-docs
  trigger:
    project: protojour/pxn/infrastructure
