name: Tests

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up cache
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linter
        run: poetry run ruff check memoriam

      - name: Pull or build Docker images
        run: docker compose -f tests/docker-compose.yml build --pull

      - name: Start docker-compose stack
        run: docker compose -f tests/docker-compose.yml up --force-recreate --remove-orphans --detach

      - name: Run integration and unit tests
        run: poetry run pytest -c pytest.ini -svv --color=yes --cov=memoriam/ --junitxml=report.xml

      - name: Stop docker-compose stack
        if: always()
        run: docker compose -f tests/docker-compose.yml down
